#+TITLE: 杂记
* 一
工作不开心。
不想多说什么了。
* 二
我发现了自己有很严重的问题。
跟好多人刚开始都玩的挺好的，但是后来都渐行渐远，互不搭理。
我经常说，这不是我的问题，但是这些人越来越遥远的时候，我觉得自己有问题。
可是我不想改，因为我很掘，我觉得我脾气已经很好了，我也不知道往什么地方去改。
* 三
谈了对象，她说，你喜欢我哪一点。
我说喜欢你好看,balabala。
她说，我想听到的答案是，你不是因为我其他的方面喜欢我，而是喜欢我本人，当我没有了其他的那些方面，你还是会喜欢我，如果没有了其他那些东西，你可能就不会喜欢我了。
我理解不了，喜欢就是感觉，没那么多讲究。
但是，后来，我发现，大家喜欢找我聊天，是因为我相对他们来说，比较厉害，如果我不厉害，什么也不会，毕业回家里混日子，他们就不会喜欢找我聊天，就不会跟我做朋友了。
我仿佛也限入了这个死胡同里。
* 四
跟发小吵了几次架。
狗日的老磨叽到大晚上，不让老子睡觉，这事吵了好几次了。
不改。
那就去tm吧。
* 五
看了过得刚好，里面有句话说，过了一段时间再回头看看自己写的文字，就会发现那些事情都显得没有那么重要了。比如我现在，觉得上边的吐槽，确实没有那么重要。
* 六
脑子有点问题，办事又很二的人，可以给于其帮助，但是不能成为朋友，而且要处处防备，不允许其与你的亲人有任何交集。
* 七
你有什么让我喜欢的地方？抱歉，我没有。
* 八
如果心烦，可以用其他事情填充自己，你有很多可以去做的事，比如
- 学吉他，弹那种很好听的音乐简直是治愈。
- 看书，好多书还没看完，如自私的基因，过得刚好。
- 刷题，题到用时方恨少。
- 约同一个城市的朋友出来吃饭，聊聊最近的状况，大家互相帮助，相遇不宜且行且珍惜。
- 打塞尔达，这个switch的游戏，够你打很长时间了吧，后边再买个传说之下。
- 和不同城市的朋友聊聊天，免得生疏。
- 学学做做饭啊。

* 九
减肥这个事情断断续续持续了好久，总是以失败告终，思考了下原因。经常会经历以下斗争：
1. 决定减肥-> 太饿 -> 工作不开心，闹心，烦 -> 食物安慰。
但是其实减肥也可以简单。
1. 工作要开心，不开心就走人。
2. 坚持，什么事情都会积小成多,比如你经常说，最后一次吃这个饭了，结果过了一段时间不高兴了，又要去吃。坚持一件事真的挺不容易。
3. 解决阻碍。如:油腻食品少吃。
* 十
有时候想通过视频来记录自己的生活，但奈何没有那种拍视频的技术。但我有笔记啊，所以即便是笔记记录了很多不好的话，也不要删，未来还是可以回味，回头看看当年的自己。
* 十一
不做缺德事，针对不认识的人，做个脸皮厚，不讲理的，不容易说话的人。
* 十二
多年后，可能会对下一代的人说，"时间很短，要珍惜时间",那这个珍惜时间的真正含义是什么呢，怎么做才算是珍惜时间呢。后来想通了，其实大人跟后人说珍惜时间，就是让你好好学习,获得相应的成就,重点是有所成就。
* 十三
有时候觉得人间其实就是天堂，而真实的人间，比现在的人间更痛苦。
* 十四
降低期望，你会变得更加快乐，更加通透。就拿北京租房这个事来说，一年换了5次房，哪次是没有问题的？不是这有缺点就是那有缺点，而你又没钱买房，没钱整租，你只能忍。那如果你降低期望了呢，一开始就知道北京租房就没有让你很安心的，你是不就好受点呢，你可能从一开始就不会换房子。
* 十五
有些事情真的是特别明显，但是你老喜欢去纠结，去细想这个事情，导致你优柔寡断的，老胡思乱想。比如别人不喜欢和你这样的直男聊天，但你却不甘心，还想用xxx打动人家啥的，就尬聊，那你不就是傻逼吗。根本就不要想，不喜欢就是不喜欢，你做什么都不行。明显的事情别纠结，断了就断了。纠结个鸡毛。

