#+TITLE: 杂记
* 一
工作不开心。
不想多说什么了。
* 二
我发现了自己有很严重的问题。
跟好多人刚开始都玩的挺好的，但是后来都渐行渐远，互不搭理。
我经常说，这不是我的问题，但是这些人越来越遥远的时候，我觉得自己有问题。
可是我不想改，因为我很掘，我觉得我脾气已经很好了，我也不知道往什么地方去改。
* 三
谈了对象，她说，你喜欢我哪一点。
我说喜欢你好看,balabala。
她说，我想听到的答案是，你不是因为我其他的方面喜欢我，而是喜欢我本人，当我没有了其他的那些方面，你还是会喜欢我，如果没有了其他那些东西，你可能就不会喜欢我了。
我理解不了，喜欢就是感觉，没那么多讲究。
但是，后来，我发现，大家喜欢找我聊天，是因为我相对他们来说，比较厉害，如果我不厉害，什么也不会，毕业回家里混日子，他们就不会喜欢找我聊天，就不会跟我做朋友了。
我仿佛也限入了这个死胡同里。
* 四
跟发小吵了几次架。
狗日的老磨叽到大晚上，不让老子睡觉，这事吵了好几次了。
不改。
那就去tm吧。
* 五
看了过得刚好，里面有句话说，过了一段时间再回头看看自己写的文字，就会发现那些事情都显得没有那么重要了。比如我现在，觉得上边的吐槽，确实没有那么重要。
* 六
脑子有点问题，办事又很二的人，可以给于其帮助，但是不能成为朋友，而且要处处防备，不允许其与你的亲人有任何交集。
* 七
你有什么让我喜欢的地方？抱歉，我没有。
* 八
如果心烦，可以用其他事情填充自己，你有很多可以去做的事，比如
- 学吉他，弹那种很好听的音乐简直是治愈。
- 看书，好多书还没看完，如自私的基因，过得刚好。
- 刷题，题到用时方恨少。
- 约同一个城市的朋友出来吃饭，聊聊最近的状况，大家互相帮助，相遇不宜且行且珍惜。
- 打塞尔达，这个switch的游戏，够你打很长时间了吧，后边再买个传说之下。
- 和不同城市的朋友聊聊天，免得生疏。
- 学学做做饭啊。

* 九
减肥这个事情断断续续持续了好久，总是以失败告终，思考了下原因。经常会经历以下斗争：
1. 决定减肥-> 太饿 -> 工作不开心，闹心，烦 -> 食物安慰。
但是其实减肥也可以简单。
1. 工作要开心，不开心就走人。
2. 坚持，什么事情都会积小成多,比如你经常说，最后一次吃这个饭了，结果过了一段时间不高兴了，又要去吃。坚持一件事真的挺不容易。
3. 解决阻碍。如:油腻食品少吃。
* 十
有时候想通过视频来记录自己的生活，但奈何没有那种拍视频的技术。但我有笔记啊，所以即便是笔记记录了很多不好的话，也不要删，未来还是可以回味，回头看看当年的自己。
* 十一
不做缺德事，针对不认识的人，做个脸皮厚，不讲理的，不容易说话的人。
* 十二
多年后，可能会对下一代的人说，"时间很短，要珍惜时间",那这个珍惜时间的真正含义是什么呢，怎么做才算是珍惜时间呢。后来想通了，其实大人跟后人说珍惜时间，就是让你好好学习,获得相应的成就,重点是有所成就。
* 十三
有时候觉得人间其实就是天堂，而真实的人间，比现在的人间更痛苦。
* 十四
降低期望，你会变得更加快乐，更加通透。就拿北京租房这个事来说，一年换了5次房，哪次是没有问题的？不是这有缺点就是那有缺点，而你又没钱买房，没钱整租，你只能忍。那如果你降低期望了呢，一开始就知道北京租房就没有让你很安心的，你是不就好受点呢，你可能从一开始就不会换房子。
* 十五
有些事情真的是特别明显，但是你老喜欢去纠结，去细想这个事情，导致你优柔寡断的，老胡思乱想。比如别人不喜欢和你这样的直男聊天，但你却不甘心，还想用xxx打动人家啥的，就尬聊，那你不就是傻逼吗。根本就不要想，不喜欢就是不喜欢，你做什么都不行。明显的事情别纠结，断了就断了。纠结个鸡毛。

* 十六
找对象的事，不用着急，最惨的不就是单一辈子吗。慢慢来，慢慢遇。不需要像舔狗那样卑微。曾经一段时间，被周围的人影响，有对象的有对象，没对象的的找不到对象，周围的比我年龄小的结婚了，周围的朋友都有了对象，就剩自己了，考虑到未来的各种可能性，于是就尝试去找对象，加入一些相亲群，加了一个妹子聊天，真的就像一个舔狗一样跟人聊天，正着反着夸，但你本来就不是这样的人啊。没必要这么卑微，尝试过后，发现这种事情不适合自己,不要被这浮躁的社会影响，好好做自己，别急躁，别瞎xx浪。你就相信上天自有安排，最坏的打算就是做个单身贵族就完了。
* 十七
郭德纲说：有些事情能烂在肚子里，不要跟任何人讲，跟任何人讲其实就是跟世界公布。
* 十八
有人说：看一个人品味高不高，就看他对象。他对象如果只是漂亮，没有任何其他优点，那这个人品味就不高。如果他对象又漂亮又很有学识，那这个人品味就相当高。打破这个法则唯一方法就是不找对象。
* 十九
每个人那都有渊博的大道理，你看这个贴子下面，每条都很有道理: https://www.v2ex.com/t/607631
* 二十
你的想法在别人那屁也不是，负能量可以吐露，但真实想法，不要说，不要说我觉得，不要说我感觉,不要说我计划，不要说自己任何的真实想法，不要标新立异。
* 二十一
让你多读书就是让你少想事。
* 二十二
人总是会怀念。比如怀念大学的某人，但是真让你回到大学做选择的时候，你依然会选择原先不变的路。你现在能怀念到的，都是一些美好的事情，但是当你真的回去的时候，你会发现有很多体验很糟糕的事情。所以不要怀疑，当下你觉得某个人很糟糕，过了一段时间后，你再回味，你会觉得这个人实际还不错。
* 二十三
昨天大学同学聚餐(时隔1年)，大家坐在一起聊天，大部分的话题都是在找对象上，这些成年人，都很优秀，在自己优秀的基础上，想找一个更优秀的TA，但是在外人看来，真的太难了。成年人找对象已经不像年轻的时候那么纯粹了，完全是在以投资的方式去寻找猎物。这种恋爱真的快乐吗。还不如充实自己，让自己更优秀，即便是单身。
* 二十四
很多人眼里，长得好看的才叫人，长得不好看的基本不在他们眼里。你在心理学里必定也能找到这种理念，每个人都有一定的价值，长得好看的本身就是一种价值，而长得不好看的只能通过其他手段来丰富自己的价值，比如有钱。但是如果一个人把这种俗的观念表现在脸面上，或者无意的展现出来，或者以此为荣并向他人展露自己观点，就很没素质很低级，很不招人喜欢。
很多人，只可远观。
男生只有在有身高的时候才会被当人。而没身高没颜值的时候，只能有强大的心理能拯救了。
这个世界的很多金句，很多甜美的爱情，很多礼物，都是为了那些被当做人的人准备的。
大部分情况下，每个人都觉得自己体面，但实际上每个人都不体面。
每个人都会希望别人重视自己。但自己有什么值得别人重视的呢。
很多人不明白自己的定位，但至少我自己能明白。
强大到一个人活的比两个都要精彩。
所以什么都会，做饭，弹吉他，学习，旅游，滑雪，看书，看电影，有自己的规划，自己跟自己吵架。
* 二十五
思考未来的世界是什么样的。这个世界为什么没有你的一碗粥。你虽然不知道你的未来是什么样的，但是你可以知道你小时候的未来是什么样的。如果让你想象你现在还处在小时候的日子里，你会想到今天的世界是这样的吗。但是仔细思考，20年前的世界和现在似乎没什么两样。注意力集中的想象一下，到现在为止比较大的改观有哪些:
1. 电脑变薄了。
2. 手机智能了。
3. 吃的油腻了。
4. 家具更新换代了。
5. 单车、平衡车。
6. 互联网发达了。
7. 智能家居来了。
8. 电动汽车来了。
似乎改变这个世界的，更多的还是互联网。汽车、自行车、空调并没有什么大的改观。但是考虑一下20年后的世界，什么物品还会改变呢。
* 二十六
有很多慢性死亡的流程，如让你娱乐至死，让你体验到油炸的快乐，吃多了慢性膨胀死，让你富有责任感，给你加大工作量，疲劳至死。
很多事情都能阻止你成长。
