#+TITLE: 悟

* 胡说八道
+ 专家不轻易在网上讨论，给小白普及知识的一般不是专家。某个知识普及火了，专家会站出来纠错。
+ 听音乐的时候会思考自己与世界格格不入，只不过因为你有一己思欲罢了，你想过的快乐奢侈，但你不努力，没有得到自己想要的，所以你难过，你用音乐来麻痹自己。你听了音乐就觉得自己是对的，自己是可怜人，但你其实是自食恶果。你是一坨屎。
+ 天生一物必有用，摘自《软技能》，其在说明，不要迷恋一门你喜欢的技术，不要因为你喜欢的技术的优秀而去抨击其他技术。同理，也可放在生活中。
+ 这世间的人，有病是正常，没病才有病,无论精神还是身体上。所以朋友做的有些出格的事，你除了骂 ，还要忍。
+ 你觉得你正常，别人并不觉得，所以说人都是不能互相理解的。虽然你有很高的成就，照样不影响你在别人心中是傻比的形象。不要太清高自傲，不要解释太多，越解释，越傻屌。心里有什么个性独特的想法就藏着捏着,不要彰显你与别人的不同。
+ 人只要在网上，就容易被带跑偏，不管你是否有独立思考的能力，照样会被带着跑，只是被带着跑的程度不同而已。
+ 衡量你现在做的事情，要考虑到未来的收益。
+ 人是利益驱动，这不奇怪，即使是做点很无赖的事情。
+ 你很菜，不要炫耀，你没有什么值得炫耀的，你炫耀的对象可能就是低调的巨巨。
+ 你因为遇到了一些世界不美好的事情，你就觉得这个世界很黑暗，那是因为你太悲观，因为悲观，你遇到不美好的事情，你会更加相信这个世界不美好，如此循环，你会很不高兴。考虑换种思考方式吧，如果碰见美好的事情，要相信这个事情的美好，不要上来就质疑，不要骂，不要觉得自己看透了人生，不要站在道德至高点去评价，不要把人心都想得那么坏，做个追求美好的人。不要因为老鼠屎影响了自己的好心情。换种思考方式，换种思考方式，换种思考方式。
+ 过得刚好说得好，开心就笑，不开心过一会再笑。人的一辈子很短暂，开心快乐最重要。管人家想什么呢，是不，自己开心最重要。
+ 自信，无所畏惧。
+ 一条核心,找准核心。
+ 不用担心未来。一切都会好的。活着就好。
+ 不要和不重要的人计较，不要和低一层级的人计较，不要浪费时间，他们说什么都对，尽管夸就对了。有句话叫和sb争论，你就是sb.
+ 人无完人，若是发现志同道合的朋友，可以交朋友，要珍惜，不能因为人家一点点的缺点就嫌弃。你可发现，到现在为止，和你三观相似的朋友没多少个。
+ 一切烦恼都是来源于穷。有时候想买的东西汇聚到一个时间点，但是不敢买，比如要租房，比如生病，比如想买个电脑，比如想报个吉他班。所以一定要好好赚钱，总有需要用到的时候。
+ 如果能像大张伟那样活的通透多好啊，别人骂他也不理，他也不管，他自己活得开心就好，这最后气的还是骂他的人。
+ 你懂的越多，懂你的越少.摘录网易云评论，共鸣。
+ 很多烦恼都是来源于穷和懒。穷不能立马解决，但是懒却可以。
