#+TITLE: 工作上的那些事情

* 记1
工作的时候，经常会这么想，我现在的这个工作是不是一个很好的工作，我要努力了，会不会是一个咸鱼翻身的机会，如果没抓住机会，会不会日后非常后悔，或许我抓住机会就会混得很好?所以很多时候，就很珍惜当前的工作，加班，刻意得去评估自己的表现，非常希望自己能够表现的很优秀，等打绩效的时候，也希望没那么差劲就好。
可是，无论怎样，你都是这沧海一粟的尘埃，历史的长河根本不关心你是否抓住的机会，而你关心的是，你生活的是否快乐，所以小哥，遵从内心，不要被工作给压垮。工作你已经做得很好了，不需要盲目接受外界的瞎tm评判。
谁tm说你工作不努力，工作做的不好，那tm就是想压榨你，凭你自己良心说，工作的就是挺不错，谁说不好都没用。
* 记2
有一天,一个二本朋友跟他舍友聊天,夸我说我找到了一个好工作,月薪上万, 他舍友来了一句,牛逼啊,前途无量啊.我当时觉得,和他们比起来确实稍微牛逼,就倍感骄傲,但是后来再仔细品位,这个前途无量的字眼格外扎心,略觉心酸.对于他们来说,找到个好工作,月薪上万,可能就前途无量了,他们有这种感觉,是因为没站到这个高度.可是站到这个高度之后,才能体会到,这个前途无量是多么难以实现.作为一个程序员,每天过着被安排的重复的日子,技术得不到提升,等到上40岁之后,学习能力没有别人强,要管理没管理,要学历没学历,还能拿什么跟别人比拼呢.但是他们好快乐..
* 记3
世间杂事千千万，你不去干谁去干.
* 记4
能遇到听得进去下面人的建议的领导，已经非常不容易了。现在已经是年轻人的时代，年轻人的想法一般都比较新颖，且创意也能吸引到更多的年轻人，代沟一代代的形成，还用老的思维方式去打斗，势必是会出问题的，但是上边的人一般都是身经百站的，不愿意折腾。假如我能走到更高的职级，希望我能成为愿意听且愿意采纳下面人的建议的人。
* 记5
我考虑了这么一件事，平常在学校还是在工作上，一件事办完的效率通常是非常高效的，但为什么现在感觉这么无力呢。仔细想了想，不是你觉得无力，而是这个事情太复杂，虽然这个事情实质上不需要你干很多，但仅仅因为他是跨部门合作的事情。一旦涉及到跨部门，你就要以pm的身份去推动各方的发展，阻止你效率高的往往就是这么个杀手，要么事情杂,要么跨部门,真是去他妈。
* 记6
今天听了部门项目的汇报会，向上级汇报近期的工作。领导说了一句话，印象深刻，我们做的事情掌握的核心是什么。核心是什么，这是一个相当好的问题，你可以做的事情，别人也可以做，但你做一个事情，一定要有别人做不了的，这样一个项目才能长久发展，这就是一个核心。当然这个理论也可以引用到工作及生活中去，你工作的时候，你的工作是否有不可替代性，如果没有，你就是可有可无的角色，要考虑一个你站得住脚的业务，深入发展。
